services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # ルートユーザーのパスワード
      MYSQL_DATABASE: test_db             # デフォルトで作成されるデータベース
      MYSQL_USER: test_user               # ユーザー名
      MYSQL_PASSWORD: test_password       # ユーザーのパスワード
    volumes:
      - mysql_data:/var/lib/mysql         # 永続化のためのボリューム
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf                       # 設定ファイル
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql  # 初期化スクリプト
      - ./data:/data                                                  # 取り込み用フォルダ
  mariadb:
    image: mariadb:10.6
    container_name: mariadb_container
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # ルートユーザーのパスワード
      MYSQL_DATABASE: test_db             # デフォルトで作成されるデータベース
      MYSQL_USER: test_user               # ユーザー名
      MYSQL_PASSWORD: test_password       # ユーザーのパスワード
    volumes:
      - mariadb_data:/var/lib/mysql         # 永続化のためのボリューム
      - ./docker/mariadb/my.cnf:/etc/mysql/my.cnf                       # 設定ファイル
      - ./docker/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql  # 初期化スクリプト
      - ./data:/data                                                  # 取り込み用フォルダ

volumes:
  mysql_data:
  mariadb_data: